version: '3.8'

volumes:
    rsstodolist_db_data:

services:
    rsstodolist:
        build:
            context: ../
            dockerfile: ./Dockerfile
        env_file: ../.env.docker_compose
        ports:
            - '${CONTAINER_EXT_PORT:-8080}:${PORT:-6070}'
        depends_on:
            - db

    db:
        #   image: 'mariadb:latest'
        #   env_file: ../.env.docker_compose
        #   volumes:
        #       - 'rsstodolist_db_data:/var/lib/mysql'
        #       - ../sql/rsstodolist.mysql:/docker-entrypoint-initdb.d/rsstodolist.sql
        image: 'postgres:latest'
        ports:
            - 5432:5432
        env_file: ../.env.docker_compose
        volumes:
            - 'rsstodolist_db_data/:/var/lib/postgresql/data/'
            - ../sql/rsstodolist.postgres:/docker-entrypoint-initdb.d/rsstodolist.sql
